#!/bin/bash

#SBATCH --output=slurm_logs/plottingIM%j.out

#SBATCH --error=slurm_logs/plottingIM%j.err

#SBATCH --job-name=plot

#SBATCH --partition=ioannidis

#SBATCH --mem=256Gb

#SBATCH --time=3:00:00

#SBATCH --constraint=E5-2680v4@2.40GHz

srun python code/GeneratePlots.py