#!/bin/bash

for center in 0.0 0.25 0.50 0.75
do
    for degree in 1 2 3 4
    do
        for constraints in 0 1 2 3 4
        do
            sbatch shell/test_samp $constraints $degree $center
        done
    done
done