#!/bin/bash

#SBATCH --output=slurm_logs/swdIM%j.out

#SBATCH --error=slurm_logs/swdIM%j.err

#SBATCH --job-name=swdIM

#SBATCH --partition=ioannidis

#SBATCH --time=48:00:00

srun python code/TestModule.py --estimator samplerWithDependencies --constraints $1