#!/bin/bash

#SBATCH --output=slurm_logs/samplertestIM%j.out

#SBATCH --error=slurm_logs/samplertestIM%j.err

#SBATCH --job-name=samplertestIM

#SBATCH --partition=ioannidis

#SBATCH --mem=256Gb

#SBATCH --time=48:00:00

#SBATCH --constraint=E5-2680v4@2.40GHz

srun python code/TestModule.py --estimator polynomial --constraints $1 --degree $2 --center $3
