#!/bin/bash

#SBATCH --output=slurm_logs/swdIM%j.out

#SBATCH --error=slurm_logs/swdIM%j.err

#SBATCH --job-name=swdIM

#SBATCH --partition=ioannidis

#SBATCH --mem=256Gb

#SBATCH --time=48:00:00

#SBATCH --constraint=E5-2680v4@2.40GHz

srun python code/TestModule.py --estimator samplerWithDependencies --constraints $1
