#!/bin/bash

#SBATCH --output=slurm_logs/testingIM%j.out

#SBATCH --error=slurm_logs/testingIM%j.err

#SBATCH --job-name=testIM

#SBATCH --partition=ioannidis

#SBATCH --mem=256Gb

#SBATCH --time=20:00:00

#SBATCH --constraint=E5-2680v4@2.40GHz

srun python code/TestModule.py --problemType IM --input datasets/smaller_graphs_file --estimator polynomial --degree $1 --center $2
