#!/bin/bash

#SBATCH --output=slurm_logs/altIM_samp_%j.out

#SBATCH --error=slurm_logs/altIM_samp_%j.err

#SBATCH --job-name='altIM_samp'

#SBATCH --partition=ioannidis

#SBATCH --mem=10Gb

#SBATCH --constraint=E5-2680v4@2.40GHz

srun python code/TestModule.py --problemType ALTIM --input datasets/RB1powerlaw_5000_5000_30255 --partitions datasets/RB1powerlaw_5000_5000_30255_partitions --estimator sampler --constraints 1 --samples $1 --iterations $2