#! /bin/bash

for queue in Info MMInfty
do
    for order in 1 2 3 4
    do
      	for graph in hypercube
        do
            for k in 1
            do
                sbatch ../script.sh Continuous_Greedy.py --graph_type $graph --query_nodes 20 --order_moment $order --queue_type $queue --samples 500 --estimator sample --k $k
            done
        done
    done
done
