#!/bin/bash
#SBATCH --output=slurm_logs/cascades%j.out

#SBATCH --error=slurm_logs/cascades%j.err

#SBATCH --job-name=gen_cascades

#SBATCH --partition=ioannidis

#SBATCH --mem=256Gb

srun python generateCascades.py
